name: 'secret-santa'

services:
    secret-santa:
        image: secret-santa
        container_name: secret-santa
        restart: always
        ports:
          - 6134:3000
        environment:
          - SECRET_SANTA_URL=${SECRET_SANTA_URL}
        volumes:
          - ./players/:/app/players/
          - ./templates/:/app/templates/
